### ISSUE TITLE
CG typos

### ISSUE THREAD

**Issue by orian34** [higurashi-mod/watanagashi#80]
"Truith" and "gyu"
![image](https://user-images.githubusercontent.com/12663654/40250460-a643d372-5ad6-11e8-825c-d87d5f80c23e.png)

**Comment by orian34** [comment]
I fear that this gyu will appear for every chapter. It was already in Oni(and I don't think was fixed, btw)

**Comment by enumag** [comment]
Fixed in all chapters.

**Comment by orian34** [comment]
@enumag  Got a comment about the typo, apparently it's not fixed?

**Comment by orian34** [comment]
Nevermind, wasn't released yet
